### ISSUE TITLE
Power options selection

### ISSUE THREAD

**Issue by super-ben** [na1oth/ppue#1]
This is not an issue per se, rather a question: how to select power options, like Super Senses? The help says “Super Senses doesn't do anything until you select which additional senses you have from a list.” but I can’t seem to find the list to choose from. “Immunity” is the same.

Also, “Load” doesn’t seem to work after I save a character sheet, though I’m unsure if it’s a bug or something to do with my Python environment (I’m using Ubuntu 24.04, Python 3.12.3).

**Comment by na1oth** [comment]
I'll clarify the instructions, but I treated each Sense as a Pro.  When you go to add Pros there are additional options for each Sense. 

What happens with the Load?  Do you get error messages, garbled data, does it crash, or something else?  I have a Ubuntu system, so I'll give it a try myself but the more you can tell me the better I can replicate what's happening.

**Comment by super-ben** [comment]
Thanks a lot, I checked the Pros, just couldn't/can't find these options, but it's probably my fault. I wanted to add 
- "Super Senses (Enhanced Hearing, Microscopic Vision, Telescopic Vision, X-Ray Vision)" (9 pts), for example or 
- "Immunity (Environmental, Life Support)" (6pts)

and among the Pros/Cons I see no options like these.

Regarding the Load error, I see the following errors:

```
Traceback (most recent call last):
  File "/home/user/Downloads/ppue-main/lib/cframe.py", line 85, in menuDo
    self.p.newChar()
  File "/home/user/Downloads/ppue-main/lib/char.py", line 427, in newChar
    self.setImage( file="icons/hero.png" )
  File "/home/user/Downloads/ppue-main/lib/char.py", line 375, in setImage
    self.lbl['bmp'].CopyFromBuffer(self.PC.buffer)
RuntimeError: Failed to gain raw access to bitmap data.
00:15:41: Debug: window wxMenuBar@0x1cff840 ("menubar") lost focus even though it didn't have it
```
When I click on "Load", nothing happens on the GUI, but I see this traceback consistently.

**Comment by na1oth** [comment]
I didn't list various Immunities as Pros, but that sounds like a good idea.  I might turn it into a container as well with a set of standardly chosen immunities.  Besides, you can always rename any of those if you have ones I didn't anticipate.

My wxPython is currently erroring on my Ubuntu build so I haven't had a chance to look at those errors.   Given the issues you've had and the setup issues I've had, I'm pondering doing a snap to keep it all self contained.  I've never built one before, so it's an interesting challenge.  Thoughts?

**Comment by super-ben** [comment]
Alright, thank you, then I won’t look for them.

I think a Snap, or even an AppImage would be great! I’m in a minority who doesn’t oppose them and it would make life for you and the end-users like me way easier. There are other small nitpicks I would think it should solve, so go for it, if that’s a viable option. I would prefer it for sure.
